spring.application.name=task-tracker

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.session.timeout=30m